kind: pipeline
name: default

steps:
  - name: build
    image: rikorose/gcc-cmake:latest
    commands:
      - cmake -S .
      - make
      - mv ./lmon ./lmon.bin
  - name: gitea_release
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: api_key
      base_url: https://gitea.oceancraft.ru
      files:
        - ./lmon.bin
    when:
      event: tag