kind: pipeline
name: default

steps:
  - name: build
    image: registry.oceancraft.ru/lmon-build-env:a03e92c753066113bf7c2ae799f459740a4de2a1
    commands:
      - ls /usr/lib/libhttp
      - cmake -S .
      - make
  - name: gitea_release
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: api_key
      base_url: https://gitea.oceancraft.ru
      files:
        - ./lmon
    when:
      event: tag

image_pull_secrets:
  - registry