stages:
  - build

build:
  stage: build
  image: registry.oceancraft.ru/yak/lmon-build-env:8da3fa030d0b02ce22fffa76b9d83b91525e810e
  before_script:
    # SysMetricsLib
    - git clone https://git.oceancraft.ru/yak/sysmetricslib.git
    - cd sysmetricslib
    - cmake -S .
    - make install
    - cd ..
    # LibBrd
    - git clone https://git.oceancraft.ru/yak/libbrd.git
    - cd libbrd
    - cmake -S .
    - make install
    - cd ..
  script:
    - cmake .
    - make
    - upx lmon
  artifacts:
    paths:
      - lmon